#  4.1 NumPy的ndarray：⼀种多维数组对象

In [11]:
import numpy as np


In [12]:
arr_1 = np.random.randn(10)
arr_1

array([-0.20468051, -1.72211619, -0.29191363,  0.8901105 ,  0.25298768,
        0.71639798, -1.2079557 ,  0.3576393 , -0.89210021, -0.1156973 ])

In [13]:
arr_1_slice = arr_1[5:8]
arr_1_slice

array([ 0.71639798, -1.2079557 ,  0.3576393 ])

In [14]:
arr_1_slice[:] = 99
arr_1_slice

array([99., 99., 99.])

In [15]:
arr_1

array([-0.20468051, -1.72211619, -0.29191363,  0.8901105 ,  0.25298768,
       99.        , 99.        , 99.        , -0.89210021, -0.1156973 ])

In [33]:
arr_2_pre_1 = np.random.rand(2,3,3)
arr_2_pre_1


array([[[0.47906646, 0.01150635, 0.56168669],
        [0.84140213, 0.60565136, 0.3218371 ],
        [0.28196541, 0.83720305, 0.09624705]],

       [[0.72532556, 0.81437931, 0.01978952],
        [0.65386396, 0.79069735, 0.87563723],
        [0.33846816, 0.85783981, 0.21646236]]])

In [34]:
arr_2_pre_2 = arr_2_pre_1 * 10
arr_2_pre_2

array([[[4.79066465, 0.1150635 , 5.61686694],
        [8.41402134, 6.05651358, 3.21837105],
        [2.81965406, 8.37203046, 0.96247055]],

       [[7.2532556 , 8.14379306, 0.19789519],
        [6.53863964, 7.90697349, 8.75637233],
        [3.38468165, 8.57839814, 2.16462355]]])

In [35]:
arr_2 = arr_2_pre_2.astype(int)  # 将整个数组的元素转换为整数
arr_2

array([[[4, 0, 5],
        [8, 6, 3],
        [2, 8, 0]],

       [[7, 8, 0],
        [6, 7, 8],
        [3, 8, 2]]])

In [36]:
arr_2[0]

array([[4, 0, 5],
       [8, 6, 3],
       [2, 8, 0]])

In [37]:
old_value = arr_2[0].copy()
old_value

array([[4, 0, 5],
       [8, 6, 3],
       [2, 8, 0]])

In [39]:
arr_2[0] = 42
arr_2

array([[[42, 42, 42],
        [42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  0],
        [ 6,  7,  8],
        [ 3,  8,  2]]])

In [41]:
a = arr_2[1:, 1:, 0:2]

array([[[6, 7],
        [3, 8]]])

In [46]:
a.shape

(1, 2, 2)

##布尔型索引

###布尔型数组的⻓度必须跟被索引的轴⻓度⼀致。

In [76]:
names = np.array(['Alice', 'Bob', 'Charlie', 'Diana'])
data = np.random.randn(4, 4)
names

array(['Alice', 'Bob', 'Charlie', 'Diana'], dtype='<U7')

In [65]:
data

array([[ 0.24986831,  1.37006644, -1.2705674 ,  0.83391553],
       [-1.09236604, -1.95876719,  1.30145462,  2.02800138],
       [-0.29769272, -0.08206041, -0.97929175,  0.76857618],
       [ 1.05382244, -0.9373896 ,  0.21793502, -1.37605735]])

In [66]:
names == 'Bob'

array([False,  True, False, False])

In [68]:
data[names == 'Bob',names == 'Alice']

array([-1.09236604])

In [74]:
mask = (names == 'Bob') | (names == 'Diana') & (names != 'Alice')
mask

array([False,  True, False, False])

In [70]:
names

array(['Alice', 'Bob', 'Charlie', 'Diana'], dtype='<U7')

In [85]:
names.shape

(4,)

##花式索引

In [90]:
arr_3 = np.empty((8, 4))
for i in range(8):
    for j in range(4):
        arr_3[i, j] = i + j
arr_3










array([[ 0.,  1.,  2.,  3.],
       [ 1.,  2.,  3.,  4.],
       [ 2.,  3.,  4.,  5.],
       [ 3.,  4.,  5.,  6.],
       [ 4.,  5.,  6.,  7.],
       [ 5.,  6.,  7.,  8.],
       [ 6.,  7.,  8.,  9.],
       [ 7.,  8.,  9., 10.]])

In [91]:
arr_3[[4, 3, 0, 6]]  # 选择第 4、3、0 和 6 行

array([[4., 5., 6., 7.],
       [3., 4., 5., 6.],
       [0., 1., 2., 3.],
       [6., 7., 8., 9.]])

In [95]:
arr_3[[-3]]

array([[5., 6., 7., 8.]])

In [96]:
arr_4 = np.arange(32).reshape((8, 4))
arr_4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [97]:
arr_4[[1, 5, 7], [0, 3, 1]]  # 选择 (1,0), (5,3), (7,1) 位置的元素

array([ 4, 23, 29])

##数组转置和轴对换

.T（二维）    .transpose（多维的）

In [98]:
arr_5 = np.arange(15).reshape((3, 5))
arr_5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [99]:
arr_5.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [100]:
np.dot(arr_5, arr_5.T)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [103]:
arr_6 = np.arange(16).reshape((2, 2, 4))
arr_6

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [104]:
arr_6.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

# 4.2 通⽤函数：快速的元素级数组函数
通⽤函数（即ufunc）是⼀种对ndarray中的数据执⾏元素级运
算的函数。你可以将其看做简单函数（接受⼀个或多个标量
值，并产⽣⼀个或多个标量值）的⽮量化包装器。

In [106]:
a = np.random.randn(4)
a

array([-1.32574607,  0.39422745,  0.62522334,  0.49321616])

In [107]:
b = np.random.randn(4)
b

array([-1.08591105,  0.26593469,  0.79813261,  1.17224713])

In [108]:
np.maximum(a, b)  # 元素级最大值

array([-1.08591105,  0.39422745,  0.79813261,  1.17224713])